apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudforms
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/cfvolumes-app
    server: 192.168.0.254
  persistentVolumeReclaimPolicy: Recycle
