apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local7-1g-small
  spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    nfs:
      server: 192.168.0.100
      path: /var/storage/local7
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local8-1g-small
  spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    nfs:
      server: 192.168.0.100
      path: /var/storage/local8
    persistentVolumeReclaimPolicy: Recycle
