apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv01
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/cfvolumes
    server: 192.168.0.254
  persistentVolumeReclaimPolicy: Recycle
